apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identrail-api
  namespace: identrail
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: identrail.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: identrail-api
                port:
                  number: 8080
  tls:
    - hosts:
        - identrail.example.com
      secretName: identrail-tls
